---
kind: pipeline
type: docker
name: drone-staging-production
steps:
  - name: build
    image: www.cocoyo.xin/drone-plugins/plugins/docker
    privileged: true
    pull: always
    settings:
      tags: cc/test:latest
    volumes:
        - name: temp
          path: /tmp
trigger:
  branch:
    - master
  event:
    - push
    - pull_request