---
kind: pipeline
type: docker
name: drone-staging-production
steps:
  - name: build
    image: hub.cocoyo.xin/drone-plugins/plugins/docker
    privileged: true
    pull: always
    settings:
      tag: latest
      repo: www.cocoyo.xin/cc/test
    volumes:
        - name: temp
          path: /tmp
trigger:
  branch:
    - master
  event:
    - push
    - pull_request
