---
kind: pipeline
type: docker
name: drone-staging-production
steps:
  - name: build
    image: www.cocoyo.xin/drone-plugins/plugins/docker
trigger:
  branch:
    - master
  event:
    - push
    - pull_request